module.exports  =
  AbstractExpression          : require './abstractExpression'
  AbstractPolyadicExpression  : require './abstractPolyadicExpression'
  EmptyExpression             : require './emptyExpression'
  ExpressionInterface         : require './expressionInterface'
  LogicalAnd                  : require './logicalAnd'
  LogicalNot                  : require './logicalNot'
  LogicalOr                   : require './logicalOr'
  NodeInterface               : require './nodeInterface'
  Pattern                     : require './pattern'
  PatternChildInterface       : require './patternChildInterface'
  PatternLiteral              : require './patternLiteral'
  PatternWildcard             : require './patternWildcard'
  Tag                         : require './tag'
  VisitorInterface            : require './visitorInterface'
